_target_: evals.models.dino_ft_conv.DINO
dino_name: dinov2
model_name: vitb14
output: dense-cls
layer: -1
mode: finetune
conv_layer: /data/fanry/Desktop/fmft/probe3d/exp/scannet_finetune/conv_layer_0.pth
