random_seed: 8
scale_factor: 0.25
num_corr: 1000
multilayer: False
normalize: False

neg_pair_num: 2
iter_num: 100
pair_num: -1
weight_decay: 0.0001
temperature: 0.1
select_idx: -1

defaults:
  - backbone: dinov2_b14
  - _self_